import { antidriftComplexityRules } from "./index.mjs";

const nativeRules = {
  eslint: {
    "eslint/accessor-pairs": "error",
    "eslint/array-callback-return": "error",
    "eslint/arrow-body-style": "error",
    "eslint/block-scoped-var": "error",
    "eslint/class-methods-use-this": "error",
    "eslint/complexity": "error",
    "eslint/curly": "error",
    "eslint/default-case": "error",
    "eslint/default-case-last": "error",
    "eslint/default-param-last": "error",
    "eslint/grouped-accessor-pairs": "error",
    "eslint/guard-for-in": "error",
    "eslint/id-denylist": "error",
    "eslint/id-length": "error",
    "eslint/id-match": "error",
    "eslint/logical-assignment-operators": "error",
    "eslint/max-depth": "error",
    "eslint/max-lines-per-function": "error",
    "eslint/max-nested-callbacks": "error",
    "eslint/max-params": "error",
    "eslint/max-statements": "error",
    "eslint/no-alert": "error",
    "eslint/no-array-constructor": "error",
    "eslint/no-caller": "error",
    "eslint/no-constructor-return": "error",
    "eslint/no-continue": "error",
    "eslint/no-div-regex": "error",
    "eslint/no-duplicate-imports": "error",
    "eslint/no-else-return": "error",
    "eslint/no-eval": "error",
    "eslint/no-extra-label": "error",
    "eslint/no-implicit-coercion": "error",
    "eslint/no-implied-eval": "error",
    "eslint/no-inner-declarations": "error",
    "eslint/no-iterator": "error",
    "eslint/no-label-var": "error",
    "eslint/no-labels": "error",
    "eslint/no-lone-blocks": "error",
    "eslint/no-lonely-if": "error",
    "eslint/no-multi-assign": "error",
    "eslint/no-multi-str": "error",
    "eslint/no-negated-condition": "error",
    "eslint/no-nested-ternary": "error",
    "eslint/no-new": "error",
    "eslint/no-new-func": "error",
    "eslint/no-new-wrappers": "error",
    "eslint/no-object-constructor": "error",
    "eslint/no-plusplus": "error",
    "eslint/no-promise-executor-return": "error",
    "eslint/no-proto": "error",
    "eslint/no-restricted-exports": "error",
    "eslint/no-restricted-globals": "error",
    "eslint/no-restricted-properties": "error",
    "eslint/no-return-assign": "error",
    "eslint/no-script-url": "error",
    "eslint/no-self-compare": "error",
    "eslint/no-sequences": "error",
    "eslint/no-shadow": "error",
    "eslint/no-throw-literal": "error",
    "eslint/no-unneeded-ternary": "error",
    "eslint/no-unreachable-loop": "error",
    "eslint/no-useless-call": "error",
    "eslint/no-useless-computed-key": "error",
    "eslint/no-useless-concat": "error",
    "eslint/no-useless-constructor": "error",
    "eslint/no-useless-rename": "error",
    "eslint/no-useless-return": "error",
    "eslint/no-void": "error",
    "eslint/no-warning-comments": "error",
    "eslint/object-shorthand": "error",
    "eslint/operator-assignment": "error",
    "eslint/prefer-destructuring": "error",
    "eslint/prefer-exponentiation-operator": "error",
    "eslint/prefer-named-capture-group": "error",
    "eslint/prefer-numeric-literals": "error",
    "eslint/prefer-object-has-own": "error",
    "eslint/prefer-object-spread": "error",
    "eslint/prefer-promise-reject-errors": "error",
    "eslint/prefer-regex-literals": "error",
    "eslint/prefer-template": "error",
    "eslint/radix": "error",
    "eslint/require-unicode-regexp": "error",
    "eslint/sort-imports": "error",
    "eslint/sort-keys": "error",
    "eslint/sort-vars": "error",
    "eslint/symbol-description": "error",
    "eslint/vars-on-top": "error",
    "eslint/yoda": "error",
  },
  import: {
    "import/consistent-type-specifier-style": "error",
    "import/extensions": "error",
    "import/max-dependencies": "error",
    "import/newline-after-import": "error",
    "import/no-absolute-path": "error",
    "import/no-amd": "error",
    "import/no-cycle": "error",
    "import/no-dynamic-require": "error",
    "import/no-empty-named-blocks": "error",
    "import/no-mutable-exports": "error",
    "import/no-named-default": "error",
    "import/no-self-import": "error",
    "import/no-webpack-loader-syntax": "error",
  },
  jsdoc: {
    "jsdoc/check-access": "error",
    "jsdoc/check-property-names": "error",
    "jsdoc/check-tag-names": "error",
    "jsdoc/empty-tags": "error",
    "jsdoc/implements-on-classes": "error",
    "jsdoc/no-defaults": "error",
    "jsdoc/require-param-type": "error",
    "jsdoc/require-property": "error",
    "jsdoc/require-property-description": "error",
    "jsdoc/require-property-name": "error",
    "jsdoc/require-returns-type": "error",
    "jsdoc/require-yields": "error",
    "jsdoc/no-blank-blocks": "error",
    "jsdoc/require-param-description": "error",
    "jsdoc/require-param-name": "error",
    "jsdoc/require-property-type": "error",
    "jsdoc/require-returns-description": "error",
    "jsdoc/require-throws-description": "error",
    "jsdoc/require-throws-type": "error",
    "jsdoc/require-yields-description": "error",
    "jsdoc/require-yields-type": "error",
  },
  node: {
    "node/handle-callback-err": "error",
    "node/no-path-concat": "error",
    "node/exports-style": "error",
    "node/no-exports-assign": "error",
    "node/no-mixed-requires": "error",
    "node/no-new-require": "error",
  },
  oxc: {
    "oxc/approx-constant": "error",
    "oxc/bad-array-method-on-arguments": "error",
    "oxc/bad-bitwise-operator": "error",
    "oxc/bad-char-at-comparison": "error",
    "oxc/bad-comparison-sequence": "error",
    "oxc/bad-match-all-arg": "error",
    "oxc/bad-min-max-func": "error",
    "oxc/bad-object-literal-comparison": "error",
    "oxc/bad-replace-all-arg": "error",
    "oxc/branches-sharing-code": "error",
    "oxc/const-comparisons": "error",
    "oxc/double-comparisons": "error",
    "oxc/erasing-op": "error",
    "oxc/misrefactored-assign-op": "error",
    "oxc/missing-throw": "error",
    "oxc/no-accumulating-spread": "error",
    "oxc/no-async-endpoint-handlers": "error",
    "oxc/no-barrel-file": "error",
    "oxc/no-const-enum": "error",
    "oxc/no-this-in-exported-function": "error",
    "oxc/number-arg-out-of-range": "error",
    "oxc/only-used-in-recursion": "error",
    "oxc/uninvoked-array-callback": "error",
  },
  promise: {
    "promise/catch-or-return": "error",
    "promise/no-callback-in-promise": "error",
    "promise/no-nesting": "error",
    "promise/no-new-statics": "error",
    "promise/no-return-in-finally": "error",
    "promise/no-return-wrap": "error",
    "promise/prefer-catch": "error",
    "promise/spec-only": "error",
    "promise/valid-params": "error",
  },
  react: {
    "react/checked-requires-onchange-or-readonly": "error",
    "react/forward-ref-uses-ref": "error",
    "react/jsx-boolean-value": "error",
    "react/jsx-curly-brace-presence": "error",
    "react/jsx-fragments": "error",
    "react/jsx-key": "error",
    "react/jsx-no-comment-textnodes": "error",
    "react/jsx-no-constructed-context-values": "error",
    "react/jsx-no-script-url": "error",
    "react/jsx-no-target-blank": "error",
    "react/jsx-no-useless-fragment": "error",
    "react/jsx-pascal-case": "error",
    "react/jsx-props-no-spread-multi": "error",
    "react/no-array-index-key": "error",
    "react/no-children-prop": "error",
    "react/no-danger": "error",
    "react/no-danger-with-children": "error",
    "react/no-this-in-sfc": "error",
    "react/self-closing-comp": "error",
    "react/void-dom-elements-no-children": "error",
    "react/display-name": "error",
    "react/forbid-dom-props": "error",
    "react/forbid-elements": "error",
    "react/function-component-definition": "error",
    "react/jsx-no-duplicate-props": "error",
    "react/jsx-no-undef": "error",
    "react/no-clone-element": "error",
    "react/no-did-mount-set-state": "error",
    "react/no-did-update-set-state": "error",
    "react/no-direct-mutation-state": "error",
    "react/no-find-dom-node": "error",
    "react/no-is-mounted": "error",
    "react/no-namespace": "error",
    "react/no-object-type-as-default-prop": "error",
    "react/no-react-children": "error",
    "react/no-redundant-should-component-update": "error",
    "react/no-render-return-value": "error",
    "react/no-set-state": "error",
    "react/no-string-refs": "error",
    "react/no-unsafe": "error",
    "react/no-unstable-nested-components": "error",
    "react/no-will-update-set-state": "error",
    "react/prefer-es6-class": "error",
    "react/prefer-function-component": "error",
    "react/require-render-return": "error",
    "react/state-in-constructor": "error",
  },
  typescript: {
    "typescript/adjacent-overload-signatures": "error",
    "typescript/ban-tslint-comment": "error",
    "typescript/ban-types": "error",
    "typescript/class-literal-property-style": "error",
    "typescript/consistent-generic-constructors": "error",
    "typescript/consistent-indexed-object-style": "error",
    "typescript/explicit-member-accessibility": "error",
    "typescript/method-signature-style": "error",
    "typescript/no-confusing-non-null-assertion": "error",
    "typescript/no-dynamic-delete": "error",
    "typescript/no-empty-interface": "error",
    "typescript/no-invalid-void-type": "error",
    "typescript/no-non-null-asserted-nullish-coalescing": "error",
    "typescript/no-restricted-types": "error",
    "typescript/no-unnecessary-parameter-property-assignment": "error",
    "typescript/no-var-requires": "error",
    "typescript/parameter-properties": "error",
    "typescript/prefer-enum-initializers": "error",
    "typescript/prefer-for-of": "error",
    "typescript/prefer-literal-enum-member": "error",
    "typescript/prefer-ts-expect-error": "error",
    "typescript/unified-signatures": "error",
  },
  unicorn: {
    "unicorn/catch-error-name": "error",
    "unicorn/consistent-assert": "error",
    "unicorn/consistent-date-clone": "error",
    "unicorn/consistent-empty-array-spread": "error",
    "unicorn/consistent-existence-index-check": "error",
    "unicorn/consistent-template-literal-escape": "error",
    "unicorn/custom-error-definition": "error",
    "unicorn/empty-brace-spaces": "error",
    "unicorn/error-message": "error",
    "unicorn/escape-case": "error",
    "unicorn/explicit-length-check": "error",
    "unicorn/explicit-timer-delay": "error",
    "unicorn/new-for-builtins": "error",
    "unicorn/no-abusive-eslint-disable": "error",
    "unicorn/no-accessor-recursion": "error",
    "unicorn/no-anonymous-default-export": "error",
    "unicorn/no-array-for-each": "error",
    "unicorn/no-array-method-this-argument": "error",
    "unicorn/no-array-reduce": "error",
    "unicorn/no-array-reverse": "error",
    "unicorn/no-array-sort": "error",
    "unicorn/no-await-in-promise-methods": "error",
    "unicorn/no-confusing-array-with": "error",
    "unicorn/no-console-spaces": "error",
    "unicorn/no-document-cookie": "error",
    "unicorn/no-empty-file": "error",
    "unicorn/no-hex-escape": "error",
    "unicorn/no-immediate-mutation": "error",
    "unicorn/no-instanceof-array": "error",
    "unicorn/no-instanceof-builtins": "error",
    "unicorn/no-invalid-fetch-options": "error",
    "unicorn/no-invalid-remove-event-listener": "error",
    "unicorn/no-length-as-slice-end": "error",
    "unicorn/no-lonely-if": "error",
    "unicorn/no-magic-array-flat-depth": "error",
    "unicorn/no-negated-condition": "error",
    "unicorn/no-negation-in-equality-check": "error",
    "unicorn/no-nested-ternary": "error",
    "unicorn/no-new-buffer": "error",
    "unicorn/no-single-promise-in-promise-methods": "error",
    "unicorn/no-static-only-class": "error",
    "unicorn/no-thenable": "error",
    "unicorn/no-this-assignment": "error",
    "unicorn/no-typeof-undefined": "error",
    "unicorn/no-unnecessary-array-flat-depth": "error",
    "unicorn/no-unnecessary-array-splice-count": "error",
    "unicorn/no-unnecessary-await": "error",
    "unicorn/no-unnecessary-slice-end": "error",
    "unicorn/no-unreadable-array-destructuring": "error",
    "unicorn/no-unreadable-iife": "error",
    "unicorn/no-useless-collection-argument": "error",
    "unicorn/no-useless-error-capture-stack-trace": "error",
    "unicorn/no-useless-fallback-in-spread": "error",
    "unicorn/no-useless-iterator-to-array": "error",
    "unicorn/no-useless-length-check": "error",
    "unicorn/no-useless-promise-resolve-reject": "error",
    "unicorn/no-useless-spread": "error",
    "unicorn/no-useless-switch-case": "error",
    "unicorn/no-zero-fractions": "error",
    "unicorn/number-literal-case": "error",
    "unicorn/numeric-separators-style": "error",
    "unicorn/prefer-array-find": "error",
    "unicorn/prefer-array-flat": "error",
    "unicorn/prefer-array-flat-map": "error",
    "unicorn/prefer-array-index-of": "error",
    "unicorn/prefer-array-some": "error",
    "unicorn/prefer-at": "error",
    "unicorn/prefer-bigint-literals": "error",
    "unicorn/prefer-blob-reading-methods": "error",
    "unicorn/prefer-class-fields": "error",
    "unicorn/prefer-classlist-toggle": "error",
    "unicorn/prefer-date-now": "error",
    "unicorn/prefer-default-parameters": "error",
    "unicorn/prefer-dom-node-append": "error",
    "unicorn/prefer-dom-node-dataset": "error",
    "unicorn/prefer-dom-node-remove": "error",
    "unicorn/prefer-export-from": "error",
    "unicorn/prefer-global-this": "error",
    "unicorn/prefer-import-meta-properties": "error",
    "unicorn/prefer-includes": "error",
    "unicorn/prefer-keyboard-event-key": "error",
    "unicorn/prefer-logical-operator-over-ternary": "error",
    "unicorn/prefer-math-min-max": "error",
    "unicorn/prefer-math-trunc": "error",
    "unicorn/prefer-modern-dom-apis": "error",
    "unicorn/prefer-modern-math-apis": "error",
    "unicorn/prefer-native-coercion-functions": "error",
    "unicorn/prefer-negative-index": "error",
    "unicorn/prefer-node-protocol": "error",
    "unicorn/prefer-number-coercion": "error",
    "unicorn/prefer-number-properties": "error",
    "unicorn/prefer-object-from-entries": "error",
    "unicorn/prefer-optional-catch-binding": "error",
    "unicorn/prefer-prototype-methods": "error",
    "unicorn/prefer-query-selector": "error",
    "unicorn/prefer-reflect-apply": "error",
    "unicorn/prefer-regexp-test": "error",
    "unicorn/prefer-response-static-json": "error",
    "unicorn/prefer-set-has": "error",
    "unicorn/prefer-set-size": "error",
    "unicorn/prefer-single-call": "error",
    "unicorn/prefer-spread": "error",
    "unicorn/prefer-string-raw": "error",
    "unicorn/prefer-string-replace-all": "error",
    "unicorn/prefer-string-slice": "error",
    "unicorn/prefer-string-starts-ends-with": "error",
    "unicorn/prefer-string-trim-start-end": "error",
    "unicorn/prefer-structured-clone": "error",
    "unicorn/prefer-ternary": "error",
    "unicorn/prefer-top-level-await": "error",
    "unicorn/prefer-type-error": "error",
    "unicorn/relative-url-style": "error",
    "unicorn/require-array-join-separator": "error",
    "unicorn/require-module-attributes": "error",
    "unicorn/require-number-to-fixed-digits-argument": "error",
    "unicorn/require-post-message-target-origin": "error",
    "unicorn/switch-case-braces": "error",
    "unicorn/switch-case-break-position": "error",
    "unicorn/text-encoding-identifier-case": "error",
    "unicorn/throw-new-error": "error",
  },
  vitest: {
    "vitest/consistent-test-filename": "error",
    "vitest/no-conditional-tests": "error",
    "vitest/no-import-node-test": "error",
    "vitest/prefer-called-once": "error",
    "vitest/prefer-to-be-object": "error",
    "vitest/consistent-each-for": "error",
    "vitest/consistent-test-it": "error",
    "vitest/consistent-vitest-vi": "error",
    "vitest/hoisted-apis-on-top": "error",
    "vitest/max-nested-describe": "error",
    "vitest/no-alias-methods": "error",
    "vitest/no-commented-out-tests": "error",
    "vitest/no-disabled-tests": "error",
    "vitest/no-duplicate-hooks": "error",
    "vitest/no-focused-tests": "error",
    "vitest/no-identical-title": "error",
    "vitest/no-interpolation-in-snapshots": "error",
    "vitest/no-large-snapshots": "error",
    "vitest/no-mocks-import": "error",
    "vitest/no-restricted-matchers": "error",
    "vitest/no-restricted-vi-methods": "error",
    "vitest/no-test-prefixes": "error",
    "vitest/no-test-return-statement": "error",
    "vitest/no-unneeded-async-expect-function": "error",
    "vitest/padding-around-after-all-blocks": "error",
    "vitest/padding-around-test-blocks": "error",
    "vitest/prefer-called-exactly-once-with": "error",
    "vitest/prefer-called-with": "error",
    "vitest/prefer-comparison-matcher": "error",
    "vitest/prefer-describe-function-title": "error",
    "vitest/prefer-each": "error",
    "vitest/prefer-equality-matcher": "error",
    "vitest/prefer-expect-resolves": "error",
    "vitest/prefer-expect-type-of": "error",
    "vitest/prefer-hooks-in-order": "error",
    "vitest/prefer-hooks-on-top": "error",
    "vitest/prefer-import-in-mock": "error",
    "vitest/prefer-importing-vitest-globals": "error",
    "vitest/prefer-mock-promise-shorthand": "error",
    "vitest/prefer-snapshot-hint": "error",
    "vitest/prefer-spy-on": "error",
    "vitest/prefer-strict-equal": "error",
    "vitest/prefer-to-be": "error",
    "vitest/prefer-to-contain": "error",
    "vitest/prefer-to-have-been-called-times": "error",
    "vitest/prefer-to-have-length": "error",
    "vitest/prefer-todo": "error",
    "vitest/require-awaited-expect-poll": "error",
    "vitest/require-local-test-context-for-concurrent-snapshots": "error",
    "vitest/require-to-throw-message": "error",
    "vitest/valid-describe-callback": "error",
    "vitest/valid-expect-in-promise": "error",
    "vitest/valid-title": "error",
    "vitest/warn-todo": "error",
  },
  "jsx-a11y": {
    "jsx-a11y/alt-text": "error",
    "jsx-a11y/anchor-ambiguous-text": "error",
    "jsx-a11y/anchor-has-content": "error",
    "jsx-a11y/anchor-is-valid": "error",
    "jsx-a11y/aria-activedescendant-has-tabindex": "error",
    "jsx-a11y/aria-props": "error",
    "jsx-a11y/aria-proptypes": "error",
    "jsx-a11y/aria-unsupported-elements": "error",
    "jsx-a11y/autocomplete-valid": "error",
    "jsx-a11y/click-events-have-key-events": "error",
    "jsx-a11y/control-has-associated-label": "error",
    "jsx-a11y/heading-has-content": "error",
    "jsx-a11y/html-has-lang": "error",
    "jsx-a11y/iframe-has-title": "error",
    "jsx-a11y/img-redundant-alt": "error",
    "jsx-a11y/interactive-supports-focus": "error",
    "jsx-a11y/label-has-associated-control": "error",
    "jsx-a11y/lang": "error",
    "jsx-a11y/media-has-caption": "error",
    "jsx-a11y/mouse-events-have-key-events": "error",
    "jsx-a11y/no-access-key": "error",
    "jsx-a11y/no-aria-hidden-on-focusable": "error",
    "jsx-a11y/no-autofocus": "error",
    "jsx-a11y/no-distracting-elements": "error",
    "jsx-a11y/no-interactive-element-to-noninteractive-role": "error",
    "jsx-a11y/no-noninteractive-element-interactions": "error",
    "jsx-a11y/no-noninteractive-element-to-interactive-role": "error",
    "jsx-a11y/no-noninteractive-tabindex": "error",
    "jsx-a11y/no-redundant-roles": "error",
    "jsx-a11y/no-static-element-interactions": "error",
    "jsx-a11y/role-has-required-aria-props": "error",
    "jsx-a11y/role-supports-aria-props": "error",
    "jsx-a11y/scope": "error",
    "jsx-a11y/tabindex-no-positive": "error",
  },
};

Object.assign(nativeRules.eslint, {
  "eslint/complexity": antidriftComplexityRules.complexity,
  "eslint/max-depth": antidriftComplexityRules["max-depth"],
  "eslint/max-params": antidriftComplexityRules["max-params"],
});

export const antidriftAdoptionPresets = Object.freeze(
  Object.fromEntries(
    Object.entries(nativeRules).map(([name, rules]) => [
      name,
      Object.freeze(rules),
    ]),
  ),
);

export function createAdoptionOxlintConfig({ presets }) {
  if (!Array.isArray(presets) || presets.length === 0) {
    throw new TypeError("Select at least one named adoption preset.");
  }
  for (const name of presets) {
    if (!Object.hasOwn(antidriftAdoptionPresets, name)) {
      throw new TypeError(`Unknown adoption preset: ${name}`);
    }
  }
  return {
    categories: Object.fromEntries(
      [
        "correctness",
        "nursery",
        "pedantic",
        "perf",
        "restriction",
        "style",
        "suspicious",
      ].map((name) => [name, "off"]),
    ),
    plugins: [...new Set(["eslint", ...presets])],
    rules: Object.assign(
      {},
      ...presets.map((name) => antidriftAdoptionPresets[name]),
    ),
  };
}
